name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: 4.8.1
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
loadbefore:
  - ItemFrameShops
softdepend: [Vault]
commands:
  balance:
    description: Shows your balances
    usage: /gbalance (account)
    aliases: [gbal, gmoney, bal]
  baltop:
    description: Shows the top balances of the server
    usage: /baltop (currency) (page)
    aliases: [gmoneytop, gecotop, gtop, gbaltop]
  currency:
    description: Manage the currencies.
    usage: /gcurrencies
    aliases: [gcurr, gemscurrencies, gcurrency, currencies]
  economy:
    description: Give, set or take currency.
    usage: /eco <set|take|give> <account> <amount> (currency)
    aliases: [geconomy, eco, geco, gemseconomy]
  pay:
    description: Pays another account
    usage: /pay <account> <amount> (currency)
    aliases: [gpay, gemspay]
  cheque:
    usage: /cheque
    description: Write or Redeem a cheque.
    aliases: [note, banknote]
  exchange:
    usage: /exchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]